### ISSUE TITLE
SyntaxError: invalid syntax in main.py, L117

### ISSUE THREAD

**Issue by elpimous** [reuben/ds-gui-demo#1]
Hi Reuben,
I encounter an error, trying main.py ?!

```
  File "main.py", line 117
    cmd, *args = self._queue.get()
         ^
SyntaxError: invalid syntax
```

'*' error ?

**Comment by elpimous** [comment]
other error : 

`python main.py /media/nvidia/neo_backup/elpimous_utils/output_graph.pb`

```
QXcbConnection: Failed to initialize XRandr
Qt: XKEYBOARD extension not present on the X server.
Traceback (most recent call last):
  File "main.py", line 385, in <module>
    demo = MainWidget()
  File "main.py", line 186, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by flyser** [comment]
You need to run this script using python 3.
